<h1>Knockout Test</h1>
<p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora placeat et possimus, labore corporis, aut quas facere sit reprehenderit accusantium obcaecati. Officiis facilis nam aliquam ullam placeat a itaque harum.
</p>
<div id="mk-knockout-example" data-bind="scope:'customcomponent'">
<!-- ko template: getTemplate() --><!-- /ko -->
<script type="text/x-magento-init">
{
"#mk-knockout-example": {
"Magento_Ui/js/core/app": {
"components": {
"customcomponent": {
"component": "MangoitSolutions_KoPractice/js/customComponentView"
}
}
}
}
}
</script>
</div>